language: go
go:
  - 1.9

env:
  - DEP_VERSION="0.3.2"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

script:
  - dep ensure
  - go test -v ./...
